# Generated by Django 2.0.1 on 2018-01-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publishrer',
            new_name='Publisher',
        ),
    ]
